server:
  port: 18080
  servlet:
    context-path: /service
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  compression:
    enabled: true
    min-response-size: 5120
    mime-types:
      - application/json
      - application/xml
      - application/protobuf
      - application/x-protobuf
  jetty:
    threads:
      acceptors: 2
      selectors: 4
    connection-idle-timeout: 18000

# 应用名称
spring:
  application:
    name: ServicePlatform
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
  aop:
    proxy-target-class: true
  config:
    activate:
      on-profile:
        - "@dev@"
        - "@userProfile@"

# Actuator Web 访问端口
management:
  server:
    port: 18081
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      base-path: /monitor
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always