server:
  port: 18080
  servlet:
    context-path: /service
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  compression:
    enabled: true
    min-response-size: 5120
    mime-types:
      - application/json
      - application/xml
      - application/protobuf
      - application/x-protobuf
  jetty:
    threads:
      acceptors: 2
      selectors: 4
    connection-idle-timeout: 18000

# 应用名称
spring:
  application:
    name: ServicePlatform
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
  aop:
    proxy-target-class: true
  profiles:
    active: @activeProfile@, @userProfile@

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(zBzbVkxmWezvkgFXQbB7+cipYL1J8uQHpYBA8UiAxRiSnzg7n3oHl9W1m9QMO9mT/kHOTPehKZQnSexQF7kGX4pjDrjyVjcSFYcdjKqX21ZPSlGJIxbjSGOrhdhjmjmpSj8RJN0sGZwYcEPpIUSqL0DpnaneeFgm4qMyJke4nD1rDjTEN60p7r677+JrWxEWx1K03CnADzf6VguGzaAG0bBII20msuCuQW6VkhmWEezxbzcp/BQ62e8WBr7Ymix6)
    username: ENC(jlFfDqIgZ3PTEbv9TcXqp+8dTYjfNomiKmG4Off9/Hk4Z4ocrV8MS1X9WghzTRTH)
    password: ENC(ACypfZhg5boYv1CggNcWX3EsGlI21w7fiviKT0Y7ukHSYETI+/Wazs/rFAEUOXb2)
    druid:
      initial-size: 2 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      min-idle: 2 #最小连接池数量
      max-active: 12 #最大连接池数量
      max-wait: 8000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      time-between-eviction-runs-millis: 120000 #有两个含义：1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      min-evictable-idle-time-millis: 180000  #连接保持空闲而不被驱逐的最小时间
      validation-query: SELECT 1 #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
      validation-query-timeout: 5 #单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
      test-while-idle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      pool-prepared-statements: true #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      #max-pool-prepared-statement-per-connection-size: 20 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      remove-abandoned: true
      log-abandoned: true
      log-different-thread: true
      filters: slf4j,stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
      use-global-data-source-stat: true

      #连接池管理页面
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        reset-enable: true
        allow:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
        commons-log:
          connection-log-error-enabled: true
          connection-rollback-after-log-enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
        principal-session-name: service_druid_session
        session-stat-enable: true
        session-stat-max-count: 2000
        profile-enable: true

  redis:
    host: ENC(ZIzccV3NCGW0vMVLcIQRIWu6hMZsFnBgXXQnDZsZaZBYbe9RcEeL0+VnVbCrwhpu)
    port: 6379
    password: ENC(VMpRXV4+9HPhHTim82W+y8tXvIPZNCz/HzrWHHsXyhWao9ZzBzU/bRb17cY3Adkq)
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 16
        max-wait: 2000
        max-idle: 8
        min-idle: 4
        time-between-eviction-runs: 180000
  cache:
    type: redis
    redis:
      use-key-prefix: true
      cache-null-values: false

# Mybatis 配置
mybatis-plus:
  type-aliases-package: com.hohenheim.java.serviceplatform.**.db.entity.*
  mapper-locations: classpath:/db/mapper/**/*Mapper.xml
  configuration:
    cache-enabled: false
    default-statement-timeout: 8
    map-underscore-to-camel-case: true
    use-generated-keys: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_128

# Actuator Web 访问端口
management:
  server:
    port: 18081
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      base-path: /monitor
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always