# sa-token框架配置
sa-token:
  token-name: ServicePlatformUserToken #Token名称 (同时也是cookie名称)
  timeout: 86400                       #Token有效期，单位/秒 默认30天，-1代表永久有效（当前设置为24小时）
  activityTimeout: 86400               #Token临时有效期 (指定时间内无操作就视为token过期) （当前设置为24小时）
  is-concurrent: false                 #是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-share: false                      #在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-read-cookie: false
  is-read-body: false
  is-read-head: true
  data-refresh-period: 300             #默认dao层实现类中，每次清理过期数据间隔的时间 (单位: 秒) ，默认值30秒，设置为-1代表不启动定时清理
  token-style: random-64
  token-session-check-login: true      #获取token专属session时是否必须登录 (如果配置为true，会在每次获取token专属session时校验是否登录)
  auto-renew: true                     #是否打开自动续签 (如果此值为true, 框架会在每次直接或间接调用getLoginId()时进行一次过期检查与续签操作)
  is-print: true                        #是否在初始化配置时打印版本字符画
  is-log: true

redis:
  ops:
    register-verify-code:
      keyPrefix: "account:verify:register:"
      expireSeconds: 300
    user-info:
      keyPrefix: "account:user:info:"
      expireSeconds: 3600

platforms:
  wx:
    applet:
      appId: wx055c7d6cbdca89e4
      secret: 9e4240b56f1fec522a8d81f530694e0e
      oauthUrl: https://open.weixin.qq.com/connect/oauth2/authorize
      callbackUrl: http://xxx.xx.com/auth/third/wx/auth/callback
    baseUrl: https://api.weixin.qq.com
