id-generator:
  user-id-generator:
    baseTime: 2022/08/07 00:00:00    # yyyy/MM/dd
    workerId : 1            # 0-31  (0 is reserved for server)
    workerIdBitLength : 3   # 机器码位长，决定 WorkerId 的最大值，默认值6，取值范围 [1, 19]，实际上有些语言采用 无符号 ushort (uint16) 类型接收该参数，所以最大值是16，如果是采用 有符号 short (int16)，则最大值为15。
    seqBitLength : 4        # 序列数位长，默认值6，取值范围 [3, 21]（建议不小于4），决定每毫秒基础生成的ID个数。规则要求：WorkerIdBitLength + SeqBitLength 不超过 22。
    minSeqNumber : 5        # 0-31 (0 is reserved for server)
    maxSeqNumber : 0        # 0-63 (0 is reserved for server)

# 异步任务线程池配置
async-task-thread-pool:
  core:
    core-pool-size: 2       #核心线程数
    max-pool-size: 16       #最大线程数
    keep-alive-seconds: 30  #允许线程空闲
    queue-capacity: 128     #等待队列大小
    thread-name-prefix: ServicePlatform-core-async-

retrofit:
  # 全局转换器工厂
  global-converter-factories:
    - com.github.lianjiatech.retrofit.spring.boot.core.BasicTypeConverterFactory
    - retrofit2.converter.jackson.JacksonConverterFactory

  # 日志打印配置
  global-log:
    # 启用日志打印
    enable: true
    # 全局日志打印级别
    log-level:  info
    # 全局日志打印策略
    log-strategy: body
  # 熔断降级配置
  degrade:
    # 熔断降级类型。默认none，表示不启用熔断降级
    degrade-type: sentinel
    # 全局sentinel降级配置
    global-sentinel-degrade:
      # 是否开启
      enable: false
      # 各降级策略对应的阈值。平均响应时间(ms)，异常比例(0-1)，异常数量(1-N)
      count: 8000
      # 熔断时长，单位为 s
      time-window: 10
      # 降级策略（0：平均响应时间；1：异常比例；2：异常数量）
      grade: 0